### ISSUE TITLE
ccsm does not start after compiling live ebuilds

### ISSUE THREAD

**Issue by thunderrd** [kajzersoze/compiz-reloaded-overlay#3]
Hi, I had everything working using 0.8.12, then tried building the 9999 ebuilds, and everything works except ccsm.  I see that only python-2 is to be used for ccsm, but the line:

Calculating dependencies... done!
[ebuild   R   *] x11-misc/ccsm-9999::compiz-reloaded-overlay  USE="-gtk3" PYTHON_TARGETS="python2_7" 0 KiB

seems to indicate that *is* happening.

Any suggestions on why I can't open ccsm?  Here is the error:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/ccsm", line 26, in <module>
    gi.require_version('Rsvg', '2.0')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available

Thank you and Happy New Year.

**Comment by kopr12** [comment]
Hmm, I'm using 9999 as well and it's working fine, seems like gnome-base/librsvg is the problem, you should have that lib already installed (it's a dependency for ccsm if it was not already installed) , can you check if you have that library installed ?
Are you running gentoo or something else maybe ?
If latter it could be the introspection USE flag.

**Comment by thunderrd** [comment]
Yup.
I have introspection disabled globally, so setting it per-package for the librsvg package and rebuilding the package solves the issue.
Thanks for the tip.

Regards and Happy New Year!

**Comment by thunderrd** [comment]
On Gentoo, BTW.

**Comment by kopr12** [comment]
Glad it worked, I asked about distribution because I think Funtoo has introspection USE flag disabled globally (if I'm not mistaken) and on Gentoo it's enabled by default. Anyway, clearly I didn't think about what happens if someone manually disables introspection, I'll see about fixing that.

Happy New Year!
