### ISSUE TITLE
compiz-debug-utils: New package

### ISSUE THREAD

**Issue by ethus3h** [kajzersoze/compiz-reloaded-overlay#4]
Looks like there's a new package: https://github.com/compiz-reloaded/compiz-debug-utils

I don't urgently need it or anything, but it does appear to not be in the overlay yet. :)

**Comment by kopr12** [comment]
True, it's not in the overlay, but it's not that new :)
It doesn't actually have a package (release), just two python scripts, I guess I can make a USE flag "debug" and then just place those two scripts in say /usr/bin/ 
I'm not sure, I'll probably do it tomorrow or something.
Do other distros have this one ?

**Comment by ethus3h** [comment]
well, I only just noticed it :3

IDK about other distros, but I stuck it into my overlay... https://github.com/ethus3h/wreathe-overlay/blob/master/x11-misc/compiz-debug-utils/compiz-debug-utils-9999.ebuild

**Comment by kopr12** [comment]
Well I looked more thoroughly into that one and nobody includes that, which doesn't mean much, but I don't really see a need for this, if it was packaged then yeah. Besides, if someone needs to debug it he would know how to find and use this anyway 🗡 

Thanks for the info though 👍
